Repository Hydronium-ion/Rare-Server, pull requests merged in 2020-08, with the labels that each got.

#56 좋아요 순으로 Content 정렬(내림차순)
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/codesquad/rare/domain/post/PostController.java
  src/main/java/com/codesquad/rare/domain/post/PostService.java
  src/test/java/com/codesquad/rare/domain/post/PostControllerTest.java
Labels: enhancement

#60 Feature/issue 058
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/codesquad/rare/domain/post/Post.java
  src/main/java/com/codesquad/rare/domain/post/PostController.java
  src/main/java/com/codesquad/rare/domain/post/PostDataRunner.java
  src/main/java/com/codesquad/rare/domain/post/PostRepository.java
  src/main/java/com/codesquad/rare/domain/post/PostService.java
  src/main/java/com/codesquad/rare/domain/post/request/PostCreateRequest.java
  src/main/java/com/codesquad/rare/error/GlobalExceptionHandler.java
  src/test/java/com/codesquad/rare/domain/post/PostControllerTest.java
  src/test/java/com/codesquad/rare/domain/post/PostServiceTest.java
  src/test/java/com/codesquad/rare/domain/post/request/PostCreateRequestTest.java
Labels: enhancement, refactoring

#70 공개된 레파지토리에서 민감한 정보 숨기기
  .github/workflows/CI-BE.yml
  build.gradle
  src/main/java/com/codesquad/rare/config/JasyptConfig.java
  src/main/resources/application.yml
  src/test/java/com/codesquad/rare/RareApplicationTests.java
  src/test/java/com/codesquad/rare/domain/post/PostControllerTest.java
  src/test/resources/application.yml
Labels: enhancement

#72 8월 1주차
  .github/workflows/CI-BE.yml
  build.gradle
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/codesquad/rare/config/JasyptConfig.java
  src/main/java/com/codesquad/rare/domain/post/Post.java
  src/main/java/com/codesquad/rare/domain/post/PostController.java
  src/main/java/com/codesquad/rare/domain/post/PostDataRunner.java
  src/main/java/com/codesquad/rare/domain/post/PostRepository.java
  src/main/java/com/codesquad/rare/domain/post/PostService.java
  src/main/java/com/codesquad/rare/domain/post/request/PostCreateRequest.java
  src/main/java/com/codesquad/rare/error/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/codesquad/rare/RareApplicationTests.java
  src/test/java/com/codesquad/rare/domain/post/PostControllerTest.java
  src/test/java/com/codesquad/rare/domain/post/PostServiceTest.java
  src/test/java/com/codesquad/rare/domain/post/request/PostCreateRequestTest.java
  src/test/resources/application.yml
Labels: enhancement

#83 [#73] Modify : 배포 시 로그 확인을 위해 코드 수정
  deploy.sh
Labels: bug, infra

#84 CodeDeploy 버그 수정을 위해 쉘스크립트 수정
  deploy.sh
Labels: bug, infra

#85 배포 스크립트와 appspec 에 beforeInstall 추가
  appspec.yml
  beforeInstall.sh
  deploy.sh
Labels: bug, infra

#86 배포 스크립트와 appspec 에 beforeInstall 추가
  appspec.yml
  beforeInstall.sh
  deploy.sh
Labels: bug, infra

#87 Jasypt 암호화로 인해 돌아가지 않는 인프라 수정
  beforeInstall.sh
  build.gradle
  src/main/java/com/codesquad/rare/config/JasyptConfig.java
Labels: bug, infra

#88 Jasypt 암호화로 인해 돌아가지 않는 인프라 수정
  beforeInstall.sh
  build.gradle
  src/main/java/com/codesquad/rare/config/JasyptConfig.java
Labels: bug, infra

#89 appspec.yml 변경
  appspec.yml
Labels: bug, infra

#90 appspec.yml 수정
  appspec.yml
Labels: bug, infra

#91 runas 권한 변경
  appspec.yml
Labels: bug, infra

#92 runas 권한 변경
  appspec.yml
Labels: bug, infra

#93 Modify : Jasypt 문제로 관련 코드 삭제. 그리고 암호화를 위해 암호화가 필요한 것들 환경변수로 설정
  appspec.yml
  beforeInstall.sh
  build.gradle
  deploy.sh
  src/main/java/com/codesquad/rare/config/JasyptConfig.java
  src/main/resources/application.yml
Labels: bug, infra

#94 Modify : Jasypt 문제로 관련 코드 삭제. 그리고 암호화를 위해 암호화가 필요한 것들 환경변수로 설정
  appspec.yml
  beforeInstall.sh
  build.gradle
  deploy.sh
  src/main/java/com/codesquad/rare/config/JasyptConfig.java
  src/main/resources/application.yml
Labels: bug, infra
