Repository Hydronium-ion/Rare-Server, pull requests merged in 2020-07, with the labels that each got.

#14 서버 CI 기능 추가
  .github/workflows/CI-BE.yml
  appspec.yml
  deploy.sh
Labels: enhancement

#15 서버 CD 기능 추가
  .github/.workflows/CD-BE.yml
Labels: enhancement

#18 서버 CD 기능 추가2
  .github/workflows/CD-BE.yml
Labels: enhancement

#21 프로젝트 설정
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: setting

#22 [#4] Fix : CD master branch에 push 되었을 경우에 동작하도록
  .github/workflows/CD-BE.yml
Labels: setting

#23 1주차 프로젝트 환경 설정
  .github/ISSUE_TEMPLATE/custom.md
  .github/workflows/CD-BE.yml
  .github/workflows/CI-BE.yml
  .gitignore
  appspec.yml
  build.gradle
  deploy.sh
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/codesquad/rare/RareApplication.java
  src/main/resources/application.yml
  src/test/java/com/codesquad/rare/RareApplicationTests.java
  src/test/resources/application.yml
Labels: setting

#24 AWS CodeDeploy 애플리케이션 수정
  .github/workflows/CD-BE.yml
Labels: setting

#25 AWS CodeDeploy 자동 배포 시 Client(or Server) 디렉토리 사라지는 현상 해결 Test
  .github/workflows/CD-BE.yml
Labels: setting

#26 Post 엔티티, Spring Rest Docs 기본 설정, Post 메인페이지(최신순으로 정렬기능)
  build.gradle
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/codesquad/rare/common/BaseTimeEntity.java
  src/main/java/com/codesquad/rare/common/api/ApiError.java
  src/main/java/com/codesquad/rare/common/api/ApiResult.java
  src/main/java/com/codesquad/rare/config/WebConfig.java
  src/main/java/com/codesquad/rare/domain/Account.java
  src/main/java/com/codesquad/rare/domain/Like.java
  src/main/java/com/codesquad/rare/domain/Tag.java
  src/main/java/com/codesquad/rare/domain/post/Post.java
  src/main/java/com/codesquad/rare/domain/post/PostController.java
  src/main/java/com/codesquad/rare/domain/post/PostDataRunner.java
  src/main/java/com/codesquad/rare/domain/post/PostRepository.java
  src/main/java/com/codesquad/rare/domain/post/PostService.java
  src/main/java/com/codesquad/rare/error/GlobalExceptionHandler.java
  src/main/java/com/codesquad/rare/error/exeception/NotFoundException.java
  src/main/java/com/codesquad/rare/error/exeception/ServiceRuntimeException.java
  src/main/resources/application.yml
  src/test/java/com/codesquad/rare/domain/post/PostControllerTest.java
Labels: enhancement, setting

#38 Feature/issue 037
  src/main/java/com/codesquad/rare/config/WebConfig.java
  src/main/java/com/codesquad/rare/domain/account/Account.java
  src/main/java/com/codesquad/rare/domain/account/AccountRepository.java
  src/main/java/com/codesquad/rare/domain/post/Post.java
  src/main/java/com/codesquad/rare/domain/post/PostDataRunner.java
  src/test/java/com/codesquad/rare/document/utils/ApiDocumentUtils.java
  src/test/java/com/codesquad/rare/domain/post/PostControllerTest.java
Labels: enhancement

#42 [#38] Feat : createdTimeAt 변수명 수정
  src/main/java/com/codesquad/rare/domain/post/Post.java
  src/main/java/com/codesquad/rare/domain/post/PostDataRunner.java
  src/main/java/com/codesquad/rare/domain/post/PostRepository.java
  src/main/java/com/codesquad/rare/domain/post/PostService.java
  src/test/java/com/codesquad/rare/domain/post/PostControllerTest.java
Labels: enhancement

#48 포스트 생성/삭제 기능 구현 및 Spring Rest Docs 문서 추가
  build.gradle
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/codesquad/rare/domain/account/Account.java
  src/main/java/com/codesquad/rare/domain/post/Post.java
  src/main/java/com/codesquad/rare/domain/post/PostController.java
  src/main/java/com/codesquad/rare/domain/post/PostRepository.java
  src/main/java/com/codesquad/rare/domain/post/PostRequestDto.java
  src/main/java/com/codesquad/rare/domain/post/PostService.java
  src/test/java/com/codesquad/rare/domain/post/PostControllerTest.java
  src/test/java/com/codesquad/rare/domain/post/PostServiceTest.java
Labels: enhancement

#54 Feature/issue 052
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/codesquad/rare/domain/post/Post.java
  src/main/java/com/codesquad/rare/domain/post/PostController.java
  src/main/java/com/codesquad/rare/domain/post/PostService.java
  src/main/java/com/codesquad/rare/domain/post/request/PostCreateRequest.java
  src/main/java/com/codesquad/rare/domain/post/response/PostCreateResponse.java
  src/test/java/com/codesquad/rare/domain/post/PostControllerTest.java
  src/test/java/com/codesquad/rare/domain/post/PostServiceTest.java
Labels: enhancement, refactoring
